package de.donnerbart.inazuma.storage.cluster.storage.message;

public enum MessageType
{
	ADD_DOCUMENT,
	FETCH_DOCUMENT,
	DELETE_DOCUMENT,
	MARK_DOCUMENT_AS_READ,

	LOAD_DOCUMENT_METADATA,
	FETCH_DOCUMENT_METADATA,
	PERSIST_DOCUMENT_METADATA,

	STORAGE_PROCESSOR_IDLE,
	SHUTDOWN
}
