package storage.message;

public enum MessageType
{
	ADD_DOCUMENT,
	DELETE_DOCUMENT,
	FETCH_DOCUMENT,
	FETCH_DOCUMENT_METADATA,
	LOAD_DOCUMENT_METADATA,
	PERSIST_DOCUMENT_METADATA,
	STORAGE_PROCESSOR_IDLE
}
